name: 'SSH remote command execute'
description: 'Executing remote ssh commands'
author: 'c-schicho'
inputs:
  host:
    description: 'ssh host'
  port:
    description: 'ssh port'
    default: 22
  user:
    description: 'ssh user'
  key:
    description: 'ssh key'
  command:
    description: 'commands to execute'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'terminal'
  color: 'gray-dark'